Dishi_Web/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('dishi_user.urls', namespace="dishi_user")),
    url(r'^auth/', include('dishi_auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^activity/', include('actstream.urls')),
    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),
]

dishi_chef/urls.py
from django.conf.urls import url, include
from dishi_chef import views

# url for a kitchen
urlpatterns = [
    url(r'^$', views.chef_home, name='home'),
    url(r'^(?P<username>[\w-]+)/save_reg_form/$', views.save_chef_reg_form, name='save_reg_form'),
    url(r'^(?P<username>[\w-]+)/kitchen/', include('dishi_kitchen.urls', namespace='kitchen')),
]

templates/auth.html
{% extends 'base.html' %}

{% block main %}
 <div>
 <h1>social authentication</h1>

 <p>
   {% if user and not user.is_anonymous %}
     Hello {{ user.get_full_name|default:user.username }}!
   {% else %}
     I don’t think we’ve met before.
   {% endif %}
 </p>
 </div>
{% endblock %}

templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>dishi</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.1.2/foundation.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/motion-ui/1.1.1/motion-ui.min.css" />
    <link rel="stylesheet" href="{% static 'font/fonts.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'css/tag-it.css' %}" type="text/css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
    <header class="header">
    <!--mobile menu-->
    <div class="title-bar" data-hide-for="medium" data-responsive-toggle=
    "example-menu">
        <button class="menu-icon" data-toggle="" type="button"></button>
        <div class="title-bar-title">
            Menu
        </div>
        <div class="title-bar-right">
            <a class="add-item" data-toggle="addItemModal"><i class=
            "fa fa-pencil-square fa-lg"></i></a> <a class=
            "search-item"><i class="fa fa-search fa-lg"></i></a>
        </div>
    </div>
    <!--   Visible menu        -->
    <div class="top-bar" id="example-menu">
        <div class="top-bar-left">
            <ul class="dropdown vertical medium-horizontal menu"
            data-dropdown-menu="">
                <li class="menu-text">DISHI
                </li>
                <li>
                    <a href="#">Order</a>
                </li>
                <li>
                    <a href="testfile.html">Discover</a>
                </li>
                <li>
                    <a href="#">Kitchens</a>
                </li>
            </ul>
        </div>
        <div class="top-bar-right">
            <ul class="menu">
                <li>
                    <a class="search-item is-mobile" href="#"><i class=
                    "fa fa-search fa-lg"></i></a>
                </li>
                <li>
                    <a class="add-item is-mobile" data-open=
                    "addItemModal"><i class=
                    "fa fa-pencil-square fa-lg"></i></a>
                </li>
                <li class="btn">
                    <a class="button inv" data-toggle="inviteModal">Invite</a>
                </li>
            </ul>
        </div>
    </div>
</header>
{% block content %}

{% endblock %}


<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.js"></script>
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/foundation/6.1.2/foundation.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" charset="utf-8"></script>
<script type="text/javascript" src="{% static 'js/tag-it.js' %}" charset="utf-8"></script>
<script type="text/javascript" src="{% static "foundation/js/vendor/what-input.min.js" %}"></script>
<script type="text/javascript" src="{% static 'js/app.js' %}"></script>
</body>
</html>

templates/blog.html
{% load crispy_forms_tags %}
<!doctype html>
<html class="no-js" lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Chef Form | Welcome</title>
<link rel="stylesheet" href="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css">
</head>
<body>
 



<div class="blog-post">
<h3>Chef Form <small>sample</small></h3>

<form  method="POST" action="" enctype="multipart/form-data">{%csrf_token%}

	{{chef_form.as_p}}

	<input type="submit" value="Create kitchen">
</form>

</div>

<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
<script>
      $(document).foundation();
    </script>
</body>
</html>

templates/chef.html
{% load crispy_forms_tags %}
<!doctype html>
<html class="no-js" lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Chef Form | Welcome</title>
<link rel="stylesheet" href="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css">
</head>
<body>
 



<div class="blog-post">
<h3>Chef Form <small>sample</small></h3>

<form  method="POST" action="" enctype="multipart/form-data">{%csrf_token%}

	{{chef_form.as_p}}

	<input type="submit" value="Create kitchen">
</form>

</div>

<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
<script>
      $(document).foundation();
    </script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
    <br>

    {% if request.user.is_authenticated %}
        <div class="text-center">
            <a class="button" href="{% url "dishi_user:home" %}">get a kitchen</a>
            <h1>{{ user.username }}</h1>
        </div>
    {% else %}
        <h1>Errr</h1>
        <a class="button" href="{% url "dishi_user:dishi_chef:home" %}">get a kitchen</a>
    {% endif %}

{% endblock %}